import { DocumentProcessContextBase } from './IDocumentProcessContext';
import { NewProcessRequest } from '../models/ModelsAutoGenerated';


export class ApplicationProcessContext extends DocumentProcessContextBase {

    constructor() {
        super();
    }

    get removingIrregularitiesInstructionURI(): string {
        return this.process.additionalData ? this.process.additionalData.removingIrregularitiesInstructionURI : null;
    }

    get caseFileURI(): string {
        return this.process.caseFileURI;
    }

    get notAcknowledgedMessageURI(): string {
        return this.process.notAcknowledgedMessageURI;
    }
 
    public tryLoadApplicationProcess(serviceID: number): Promise<boolean> {
        this.clearContext();

        return this.processDataService.getDocumentProcessByServiceID(serviceID).bind(this).then(process => {
            if (process) {
                return this.initDocumentProcessContext(process).bind(this).then(() => true);
            }
            else {
                return false
            }
        })
    }

    public createApplicationProcess(serviceID: number, removingIrregularitiesInstructionURI: string, additionalApplicationURI: string, caseFileURI: string): Promise<void> {
        var request = new NewProcessRequest();
        request.serviceID = Number(serviceID);
        request.removingIrregularitiesInstructionURI = removingIrregularitiesInstructionURI;
        request.additionalApplicationURI = additionalApplicationURI;
        request.caseFileURI = caseFileURI;

        return this.processDataService.createDocumentProcess(request).bind(this).then(process => {
            return this.initDocumentProcessContext(process);
        })
    }
}