import { BaseDataModel, TypeSystem } from 'cnsys-core';
import { observable } from 'mobx';
import moment from 'moment';
import { moduleContext } from '../ModuleContext';
import { IssuerCountryVM } from './ModelsAutoGenerated';

@TypeSystem.typeDecorator('TravelDocumentVM', moduleContext.moduleName)
export class TravelDocumentVM extends BaseDataModel {

    //#region identityNumber

    @observable private _identityNumber: string = null;

    @TypeSystem.propertyDecorator('string')
    public set identityNumber(val: string) {
        this._identityNumber = val;
    }

    public get identityNumber(): string {
        return this._identityNumber;
    }

    //#endregion identityNumber 

    //#region identitityIssueDate

    @observable private _identitityIssueDate: moment.Moment = null;

    @TypeSystem.propertyDecorator('moment')
    public set identitityIssueDate(val: moment.Moment) {
        if (moment.isMoment(val))
            this._identitityIssueDate = val.startOf('day');
        else
            this._identitityIssueDate = val
    }

    public get identitityIssueDate(): moment.Moment {
        return this._identitityIssueDate;
    }

    //#endregion identitityIssueDate 

    //#region identitityExpireDate

    @observable private _identitityExpireDate: moment.Moment = null;

    @TypeSystem.propertyDecorator('moment')
    public set identitityExpireDate(val: moment.Moment) {
        if (moment.isMoment(val))
            this._identitityExpireDate = val.endOf('day');
        else
            this._identitityExpireDate = val;
    }

    public get identitityExpireDate(): moment.Moment {
        return this._identitityExpireDate;
    }

    //#endregion identitityExpireDate 

    //#region identityIssuer

    @observable private _identityIssuer: IssuerCountryVM = null;

    @TypeSystem.propertyDecorator(moduleContext.moduleName + '.' + 'IssuerCountryVM')
    public set identityIssuer(val: IssuerCountryVM) {
        this._identityIssuer = val;
    }

    public get identityIssuer(): IssuerCountryVM {
        return this._identityIssuer;
    }

    //#endregion identityIssuer 

    //#region identityDocumentSeries

    @observable private _identityDocumentSeries: string = null;

    @TypeSystem.propertyDecorator('string')
    public set identityDocumentSeries(val: string) {
        this._identityDocumentSeries = val;
    }

    public get identityDocumentSeries(): string {
        return this._identityDocumentSeries;
    }

    //#endregion identityDocumentSeries 

    constructor(obj?: any) {
        super(obj)

        this.copyFrom(obj);
    }
} 