import { EAUBaseValidator, ResourceHelpers } from "eau-core";
import { DocumentFormValidationContext, PersonAddressValidator, ErrMsgCodesConstants } from "eau-documents";
import { ApplicationForIssuingDocumentForRightsAndImposedPenaltiesOfVehicleDriverDataVM } from "../models/ModelsAutoGenerated";

export class ApplicationForIssuingDocumentForRightsAndImposedPenaltiesOfVehicleDriverDataVMValidator extends EAUBaseValidator<ApplicationForIssuingDocumentForRightsAndImposedPenaltiesOfVehicleDriverDataVM, DocumentFormValidationContext> {
    constructor() {
        super();
        
        this.ruleFor(m => m.andCertificateReason).notEmpty().withMessage(ResourceHelpers.formatErrorMessage(ErrMsgCodesConstants.DefaultNotEmptyErrorMessage, new ApplicationForIssuingDocumentForRightsAndImposedPenaltiesOfVehicleDriverDataVM(), 'andCertificateReason'));

    }
}
