import { EAUBaseDataService } from 'eau-core';
import { ANDObligationSearchCriteria, ANDObligationSearchResponse, Obligation, ObligationRequest, ObligationSearchCriteria, PaymentRequest, StartPaymentRequest } from '../models/ModelsAutoGenerated';

export class ObligationsDataService extends EAUBaseDataService {

    protected baseUrl(): string {
        return super.baseUrl() + "Obligations";
    }

    public searchObligations(criteria: ObligationSearchCriteria): Promise<Obligation[]> {

        return this.get<Obligation[]>("", Obligation, criteria, null).then(function (result: Obligation[]) {
            criteria.count = this.jqXHR.getResponseHeader('count') ? this.jqXHR.getResponseHeader('count') : 0;
            return result;
        });
    }

    /**
     * Търсене на задължения АНД
     * @param criteria 
     */
    public searchObligationsAND(criteria: ANDObligationSearchCriteria): Promise<ANDObligationSearchResponse> {
        return this.get<ANDObligationSearchResponse>("/AND", ANDObligationSearchResponse, criteria)
        .then(
            (result) => {
                return Promise.resolve(result)}
                
            );
    }

    /**
     * Добавя задължение
     * @param obligationRequest
     */
    public createObligation(obligationRequest: ObligationRequest): Promise<Obligation> {
        return this.post<Obligation>("", Obligation, obligationRequest)
            .then((result) => { 
                return result;
            });
    }

    /**
     * Стартира заявка за плащане
     * @param serviceGroup
     */
    public startPayment(startPaymentData: StartPaymentRequest, obligationId: number): Promise<PaymentRequest> {

        return this.post<PaymentRequest>(`/${obligationId}/StartPayment`, PaymentRequest, startPaymentData)
            .then((paymentRequest) => {return paymentRequest});
    }


    public ANDUndeliveredPersonObligation() {

        return false;
    }

    /**
     * Търсене на задължения
     * @param criteria 
     */
    public searchObligationsServiceInstances(criteria: ObligationSearchCriteria): Promise<Obligation[]> {
        return this.get<Obligation[]>(`/ServiceInstances`, Obligation, criteria, null).then(function (result: Obligation[])
        {
            return result;
        });    
    }
}