
import { UrlHelper } from 'cnsys-core';
import { RegistrationDataTypes } from 'eau-core';
import { PaymentRequest, ObligationStatuses, ObligationRequest, Obligation, StartPaymentRequest, ObligationTypes } from '../models/ModelsAutoGenerated';
import { ObligationsDataService } from './ObligationsDataService';

export namespace PaymentHelper {
    
    /**
     * Прави заявка към платежна система 
     * 
     * @param paymentRequest 
     */
    export function processPayment(paymentRequest: PaymentRequest) {

        switch (Number(paymentRequest.registrationDataType)) {

            case RegistrationDataTypes.ePay:

                let ePayUrl = paymentRequest.additionalData.portalUrl;

                UrlHelper.postDataToUrl(ePayUrl, {
                    "PAGE": "paylogin", 
                    "ENCODED":paymentRequest.additionalData.data, 
                    "CHECKSUM": paymentRequest.additionalData.hmac,
                    "URL_OK": paymentRequest.additionalData.okCancelUrl,
                    "URL_CANCEL": paymentRequest.additionalData.okCancelUrl
                });

            break;

            case RegistrationDataTypes.PepOfDaeu:
                let pepUrl = UrlHelper.urlJoin(paymentRequest.additionalData.portalUrl, "/vpos/payment");
                UrlHelper.postDataToUrl(pepUrl, {"clientId": paymentRequest.additionalData.clientId, "data": paymentRequest.additionalData.data, "hmac": paymentRequest.additionalData.hmac})
            break; 
        }
    }


    /**
     * Създава задължение, ако такова не съществува в нашата система, или връща вече създадено такова.
     * 
     * @param obligation 
     * @param obligationType 
     */
    export function processObligation(obligation: Obligation, obligationType): Promise<Obligation> {

        switch (Number(obligation.status)) {

            // Създаваме задължение при нас, ако такова не съществува
            case ObligationStatuses.Pending:
                let createObligatiobRequest = new ObligationRequest();
                
                createObligatiobRequest.type = obligationType;
                createObligatiobRequest.obligationDate = obligation.obligationDate;
                createObligatiobRequest.obligationIdentifier = obligation.obligationIdentifier;
                createObligatiobRequest.obligedPersonName = obligation.obligedPersonName;
                createObligatiobRequest.obligedPersonIdent = obligation.obligedPersonIdent;
                createObligatiobRequest.obligedPersonIdentType = obligation.obligedPersonIdentType;
                
                let obligationDM: ObligationsDataService;
                obligationDM = new ObligationsDataService();

                return obligationDM.createObligation(createObligatiobRequest)
                    .then(obligation => {
                        return obligation;
                });

            break;
                
            // Инициира плащане
            default:
                return Promise.resolve(obligation);
            break;
        }
    }

    /**
     * Създава заявка за плащане
     * 
     * @param obligation 
     * @param registrationDataType 
     * @param okCancelUrl 
     * @param withDiscount 
     */
    export function createPaymenRequest(obligation: Obligation, registrationDataType: number, okCancelUrl: string, withDiscount?: boolean):Promise<StartPaymentRequest>  {

        let startPaymentRequest = new StartPaymentRequest();

        startPaymentRequest.obligedPersonIdent = obligation.obligedPersonIdent;
        startPaymentRequest.obligedPersonIdentType = obligation.obligedPersonIdentType;
        startPaymentRequest.obligedPersonName = obligation.obligedPersonName;
        startPaymentRequest.registrationDataType = registrationDataType;
        startPaymentRequest.okCancelUrl = okCancelUrl;
        
        switch (Number(obligation.type)) {

            case ObligationTypes.AND:

                if (withDiscount)
                    startPaymentRequest.amount = obligation.discountAmount;
                else
                    startPaymentRequest.amount = obligation.amount;
            break;

            default:
                startPaymentRequest.amount = obligation.discountAmount;
            break;
        }
        
        return Promise.resolve(startPaymentRequest);
    }

}