import { BaseProps } from "cnsys-ui-react";
import { EAUBaseComponent } from "eau-core";
import { ApplicationFormManagerProps, withDocumentFormManager, FieldFormUI } from "eau-documents";
import { observer } from "mobx-react";
import React from "react";
import { SecurityObjectsDataVM } from "../../models/ModelsAutoGenerated";
import { SecurityObjectDataUI } from "../field-forms";

interface SecurityObjectsDataProps extends BaseProps, ApplicationFormManagerProps {
}

@observer export class SecurityObjectsDataImpl
    extends EAUBaseComponent<SecurityObjectsDataProps, SecurityObjectsDataVM> {


    renderEdit(): JSX.Element {
        return (
            <>
                <FieldFormUI title={this.getResourceByProperty(m => m.securityObjects)}>
                    <SecurityObjectDataUI {...this.bind(m => m.securityObjects)} />
                </FieldFormUI>
            </>
        );
    }

    renderDisplay(): JSX.Element {
        return (
            <>
                <FieldFormUI title={this.getResourceByProperty(m => m.securityObjects)}>
                    <SecurityObjectDataUI {...this.bind(m => m.securityObjects)} />
                    {this.propertyErrorsDispleyFor(m => m.securityObjects)}
                </FieldFormUI>
            </>
        );
    }
}

export const SecurityObjectsDataUI = withDocumentFormManager(SecurityObjectsDataImpl);