import { EAUBaseValidator } from "eau-core";
import { DocumentFormValidationContext } from "eau-documents";
import { ApplicationForIssuingResidencePermitAndDrivingLicenseForEuropeanCitizensDataVM } from "../models/ModelsAutoGenerated";
import { ForeignIdentityBasicDataValidator } from "./ForeignIdentityBasicDataValidator";
import { TravelDocumentValidator } from "./TravelDocumentValidator";

export class ApplicationForIssuingResidencePermitAndDrivingLicenseForEuropeanCitizensDataValidator
    extends EAUBaseValidator<ApplicationForIssuingResidencePermitAndDrivingLicenseForEuropeanCitizensDataVM, DocumentFormValidationContext> {

    constructor() {
        super();

        this.ruleFor(m => m.foreignIdentityBasicData).setValidator(new ForeignIdentityBasicDataValidator());
        this.ruleFor(m => m.travelDocument).setValidator(new TravelDocumentValidator());
    }
}