import { EAUBaseValidator, ResourceHelpers, resourceManager } from "eau-core";
import { DocumentFormValidationContext, ErrMsgCodesConstants } from "eau-documents";
import { PersonDataVM, ForeignIdentityBasicDataVM } from "../models/ModelsAutoGenerated";

export class ForeignIdentityBasicDataValidator extends EAUBaseValidator<ForeignIdentityBasicDataVM, DocumentFormValidationContext> {

    constructor() {
        super();

        this.ruleFor(m => m.phone).notEmpty()
            .withMessage(ResourceHelpers.formatErrorMessage(ErrMsgCodesConstants.DefaultNotEmptyErrorMessage, new ForeignIdentityBasicDataVM(), 'phone'))
        this.ruleFor(m => m.phone).isValidPhone().withMessage(resourceManager.getResourceByKey("DOC_GL_WRONG_PHONE_NUMBER_E"))

        //this.ruleFor(m => m.eyesColor).notEmpty().withMessage(ResourceHelpers.formatErrorMessage(ErrMsgCodesConstants.DefaultNotEmptyErrorMessage, new PersonDataVM(), 'eyesColor'))
        //this.ruleFor(m => m.height).notEmpty().withMessage(ResourceHelpers.formatErrorMessage(ErrMsgCodesConstants.DefaultNotEmptyErrorMessage, new PersonDataVM(), 'height'))
        //this.ruleFor(m => m.maritalStatus).notEmpty().withMessage(ResourceHelpers.formatErrorMessage(ErrMsgCodesConstants.DefaultNotEmptyErrorMessage, new PersonDataVM(), 'maritalStatus'))
    }
}