import { EAUBaseValidator, ResourceHelpers } from "eau-core";
import { DocumentFormValidationContext, ErrMsgCodesConstants } from "eau-documents";
import { IssuerCountryVM } from "../models/ModelsAutoGenerated";

export class IssuerCountryValidator extends EAUBaseValidator<IssuerCountryVM, DocumentFormValidationContext> {

    constructor() {
        super();

        this.ruleFor(m => m.countryName).notEmpty().withMessage(ResourceHelpers.formatErrorMessage(ErrMsgCodesConstants.DefaultNotEmptyErrorMessage, new IssuerCountryVM(), 'countryGRAOCode'));
    }
}