import { EAUBaseValidator, ResourceHelpers } from "eau-core";
import { DocumentFormValidationContext, ErrMsgCodesConstants } from "eau-documents";
import { PersonDataVM } from "../models/ModelsAutoGenerated";

export class PersonDataValidator extends EAUBaseValidator<PersonDataVM, DocumentFormValidationContext> {

    constructor() {
        super();

        this.ruleFor(m => m.eyesColor).notEmpty().withMessage(ResourceHelpers.formatErrorMessage(ErrMsgCodesConstants.DefaultNotEmptyErrorMessage, new PersonDataVM(), 'eyesColor'))
        this.ruleFor(m => m.height).notEmpty().withMessage(ResourceHelpers.formatErrorMessage(ErrMsgCodesConstants.DefaultNotEmptyErrorMessage, new PersonDataVM(), 'height'))
        this.ruleFor(m => m.maritalStatus).notEmpty().withMessage(ResourceHelpers.formatErrorMessage(ErrMsgCodesConstants.DefaultNotEmptyErrorMessage, new PersonDataVM(), 'maritalStatus'))
    }
}