import { AsyncUIProps, BaseProps } from 'cnsys-ui-react';
import { attributesClassFormControlReqired, EAUBaseComponent, attributesClassFormControlRequiredLabel } from 'eau-core';
import React from 'react';
import { ANDObligationSearchCriteria } from '../../models/ModelsAutoGenerated';

interface KatObligationsProps extends BaseProps, AsyncUIProps {
    validator
}

export class KatObligationsFormByIdentityUI extends EAUBaseComponent<KatObligationsProps, ANDObligationSearchCriteria>{

    constructor(props: KatObligationsProps) {
        super(props);

        this.validators = this.props.validator;
    }

    render() {
        return <>
            <div className="form-group col-sm-6 col-lg-4">
                {this.labelFor(m => m.drivingLicenceNumber, "GL_DRIVING_LICENCE_NUMBER_L", attributesClassFormControlRequiredLabel)}
                {this.textBoxFor(m => m.drivingLicenceNumber, attributesClassFormControlReqired)}
            </div>
            <div className="form-group col-sm-6 col-lg-4">
                {this.labelFor(m => m.obligedPersonIdent, "GL_PERSON_ID_L", attributesClassFormControlRequiredLabel)}
                {this.textBoxFor(m => m.obligedPersonIdent, attributesClassFormControlReqired)}
            </div>
        </>
    }
}
