import { BaseProps } from "cnsys-ui-react";
import { attributesClassFormControlLabel, attributesClassFormControlReqired, attributesClassFormControlRequiredLabel, Constants, EAUBaseComponent } from "eau-core";
import { withCollectionItems } from "eau-documents";
import React from "react";
import { Employee, EmployeeIdentifierType, RemoveEmployeeRequest } from "../../models/ModelsAutoGenerated";
import { EmployeeUI } from "./EmployeeUI";

class RemoveEmployeeRequestsImpl extends EAUBaseComponent<BaseProps, RemoveEmployeeRequest>{

    renderEdit() {
        return (
            <>
                <EmployeeUI {...this.bind(x => x.employee)} />
                <div className="row">
                    <div className="form-group col-lg-6 col-xl-7">
                        {this.labelFor(x => x.contractTerminationNumber, null, attributesClassFormControlRequiredLabel)}
                        {this.textBoxFor(x => x.contractTerminationNumber, attributesClassFormControlReqired)}
                    </div>
                    <div className="form-group col-sm">
                        {this.labelFor(x => x.contractTerminationDate, null, attributesClassFormControlRequiredLabel)}
                        {this.dateFor(x => x.contractTerminationDate)}
                    </div>
                </div>
                <div className="row">
                    <div className="form-group col-12">
                        {this.labelFor(x => x.contractTerminationEffectiveDate, null, attributesClassFormControlRequiredLabel)}
                        {this.dateFor(x => x.contractTerminationEffectiveDate)}
                    </div>
                </div>
            </>
        );
    }

    renderDisplay() {
        return (
            <>
                <EmployeeUI {...this.bind(x => x.employee)} />
                <div className="row">
                    <div className="form-group col-sm-6">
                        {this.labelFor(x => x.contractTerminationNumber, null, attributesClassFormControlLabel)}
                        {this.textDisplayFor(x => x.contractTerminationNumber)}
                    </div>
                    <div className="form-group col-sm-6">
                        {this.labelFor(x => x.contractTerminationDate, null, attributesClassFormControlLabel)}
                        <p className="field-text">{this.dateDisplayFor(this.model.contractTerminationDate, Constants.DATE_FORMATS.date)}</p>
                        {this.propertyErrorsDispleyFor(m => m.contractTerminationDate)}
                    </div>
                </div>
                <div className="row">
                    <div className="form-group col-12">
                        {this.labelFor(x => x.contractTerminationEffectiveDate, null, attributesClassFormControlLabel)}
                        <p className="field-text">{this.dateDisplayFor(this.model.contractTerminationEffectiveDate, Constants.DATE_FORMATS.date)}</p>
                        {this.propertyErrorsDispleyFor(m => m.contractTerminationEffectiveDate)}
                    </div>
                </div>
            </>
        );
    };
}

export const RemoveEmployeeRequestsUI = withCollectionItems(RemoveEmployeeRequestsImpl, {
    initItem: () => {
        let removeEmployeeRequest = new RemoveEmployeeRequest();
        removeEmployeeRequest.employee = new Employee();
        removeEmployeeRequest.employee.employeeIdentifierType = EmployeeIdentifierType.EGN;

        return removeEmployeeRequest;
    },
    addButtonLabelKey: 'GL_ADD_EMPLOYEE_CONTRACT_L'
})