import * as React from "react";
import { observer } from "mobx-react";
import { BaseProps } from "cnsys-ui-react";
import { EAUBaseComponent, attributesClassFormControlRequiredLabel, Constants } from "eau-core";
import { SecurityContractData } from "../../models/ModelsAutoGenerated";


interface SecurityContractDatProps extends BaseProps {
    mode: "new" | "term4" | "term235789";
}

@observer export class SecurityContractDataUI extends EAUBaseComponent<SecurityContractDatProps, SecurityContractData>{

    constructor(props: SecurityContractDatProps) {
        super(props);


    }

    renderEdit() {
        return (
            <>
                <div className="row">
                    {this.props.mode != "new" ?
                        <div className="form-group col-12 col-xl-7">
                            {this.labelFor(m => m.contractType, null, attributesClassFormControlRequiredLabel)}
                            {this.textBoxFor(m => m.contractType)}
                        </div>
                        : null}
                    {this.props.mode != "new" ?
                        <div className="form-group col-sm-6 col-xl-7">
                            {this.labelFor(m => m.documentNumber, null, attributesClassFormControlRequiredLabel)}
                            {this.textBoxFor(m => m.documentNumber)}
                        </div>
                        :
                        <div className="form-group col-sm-6 col-xl-7">
                            {this.labelFor(m => m.contractNumber, null, attributesClassFormControlRequiredLabel)}
                            {this.textBoxFor(m => m.contractNumber)}
                        </div>
                    }
                    <div className="form-group col-sm">
                        {this.labelFor(m => m.contractDate, null, attributesClassFormControlRequiredLabel)}
                        <div className="input-group date-control">
                            {this.dateFor(m => m.contractDate)}
                        </div>
                        <div className="sr-only" id="HELP-1">Попълнете две цифри за дата, две цифри за месец и четири цифри за година. Разделете цифрите за дата, месец и година с точка.</div>
                    </div>
                </div>
                {this.props.mode == "term235789" ?
                    <div className="row">
                        <div className="form-group col-12">
                            <div className="custom-control custom-checkbox">
                                {this.checkBoxFor(m => m.contractIsExpired)}
                            </div>
                        </div>
                    </div>
                    : null}
            </>
        );
    }

    renderDisplay() {
        return (
            <>
                <div className="row">
                    {this.props.mode != "new" ?
                        <div className="form-group col-12">
                            <h4 className="form-control-label">{this.getResourceByProperty(m => m.contractType)}</h4>
                            {this.textDisplayFor(m => m.contractType)}
                        </div>
                        : null}
                    {this.props.mode != "new" ?
                        <div className="form-group col-sm-6 col-xl-4">
                            <h4 className="form-control-label">
                                {this.getResourceByProperty(m => m.documentNumber)}
                            </h4>
                            {this.textDisplayFor(m => m.documentNumber)}
                        </div>
                        :
                        <div className="form-group col-sm-6 col-xl-4">
                            <h4 className="form-control-label">
                                {this.getResourceByProperty(m => m.contractNumber)}
                            </h4>
                            {this.textDisplayFor(m => m.contractNumber)}
                        </div>
                        }
                    <div className="form-group col-sm-6 col-xl-4">
                        <h4 className="form-control-label">{this.getResourceByProperty(m => m.contractDate)}</h4>
                        {this.dateDisplayFor(this.model.contractDate, Constants.DATE_FORMATS.date)}
                        {this.propertyErrorsDispleyFor(m => m.contractDate)}
                    </div>
                    {this.props.mode == "term235789" && this.model.contractIsExpired === true ?
                        <div className="form-group col-12">
                            <p className="field-text check-item check-success">
                                {this.getResourceByProperty(m => m.contractIsExpired)}
                            </p>
                        </div>
                        : null}
                </div>
            </>
        );
    };

}