import { EAUBaseValidator, ResourceHelpers } from "eau-core";
import { DocumentFormValidationContext, ErrMsgCodesConstants } from "eau-documents";
import { CertificateToWorkWithFluorinatedGreenhouseGassesVM } from "../../models/ModelsAutoGenerated";
import { AppForIssOrRenewCertToWorkWithFluorGreenhouseGassesPersonDataVMValidator } from "../AppForIssOrRenewCertToWorkWithFluorGreenhouseGassesPersonDataVMValidator";
import { AppForIssOrRenewCertToWorkWithFluorGreenhouseGassesEntityDataVMValidator } from "../AppForIssOrRenewCertToWorkWithFluorGreenhouseGassesEntityDataVMValidator";

export class CertificateToWorkWithFluorinatedGreenhouseGassesValidator extends EAUBaseValidator<CertificateToWorkWithFluorinatedGreenhouseGassesVM, DocumentFormValidationContext> {
    constructor() {
        super();

        this.ruleFor(m => m.personData).setValidator(new AppForIssOrRenewCertToWorkWithFluorGreenhouseGassesPersonDataVMValidator());
        this.ruleFor(m => m.entityData).setValidator(new AppForIssOrRenewCertToWorkWithFluorGreenhouseGassesEntityDataVMValidator());
        this.ruleFor(m => m.certificateToWorkWithFluorinatedGreenhouseGassesActivities).notEmpty()
            .withMessage(ResourceHelpers.formatErrorMessage(ErrMsgCodesConstants.DefaultNotEmptyErrorMessage, new CertificateToWorkWithFluorinatedGreenhouseGassesVM(), 'certificateToWorkWithFluorinatedGreenhouseGassesActivities'));
    }
}